# Generated by Django 6.0.4 on 2026-05-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('shared', 'Общий расход'), ('personal', 'Личный расход')], default='shared', max_length=20),
        ),
    ]
