# Generated by Django 6.0.4 on 2026-05-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_dayplan_tripcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
